---
title: "Advanced Shinyspring app"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Advanced Shinyspring app}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Chicago Traffic App

[Julia Silge](https://juliasilge.com/) has done excellent [analysis on chicago traffic](https://juliasilge.com/blog/chicago-traffic-model/). Let us convert this analysis into an AI App based on Shinyspring.

### AI App Goals

Before we start let us define the goals and personas for the app.

#### Goals

-   Provide *Weekly/ daily* **Statistics on Traffic Injuries** for Operational Stakeholders

-   Provide a **Prediction on "Expected Injuries**" at a *weekly/daily* level for operational stakeholders to be able to plan deployments on the field.

-   Provide a view on **factors leading to injuries**. This functionality will probably be used once in 6 months by research and industry professionals in Road construction , Insurance.

-   **Monitor the Models** and let data scientists know if the models are no longer serving the purpose they were intended for.

I find creating a persona board (as shown below) very useful to define the scope of a dashboard / AI app.

#### Personas

+-------------------------------------------------------------+------------------------------+-----------------------------------------------------------------+-------------------+-------------------+
| Persona                                                     | Frequency of visits          | Reason to visit and Use                                         | What is Awesome ? | What would suck ? |
+=============================================================+==============================+=================================================================+===================+===================+
| Operational Manager .(City Planning officials , Cops , etc) | [Weekly / Daily]{.smallcaps} | Plan Resource Deployments at various locations.                 |                   |                   |
+-------------------------------------------------------------+------------------------------+-----------------------------------------------------------------+-------------------+-------------------+
|                                                             | [Weekly / Daily]{.smallcaps} | Investigate Past Date situations as need arrives in operations. |                   |                   |
+-------------------------------------------------------------+------------------------------+-----------------------------------------------------------------+-------------------+-------------------+
| Research and Industry Professionals                         |                              | Develop a high level view on factors leading to injury          |                   |                   |
+-------------------------------------------------------------+------------------------------+-----------------------------------------------------------------+-------------------+-------------------+
| Data Scientist                                              |                              |                                                                 |                   |                   |
+-------------------------------------------------------------+------------------------------+-----------------------------------------------------------------+-------------------+-------------------+
| General Public                                              |                              |                                                                 |                   |                   |
+-------------------------------------------------------------+------------------------------+-----------------------------------------------------------------+-------------------+-------------------+
| Website Admin                                               |                              |                                                                 |                   |                   |
+-------------------------------------------------------------+------------------------------+-----------------------------------------------------------------+-------------------+-------------------+

**Note**: While the above persona board serve's its purpose for this document ,it is a very basic L1 level board. In a real life situation much more details are needed and each line-item needs to be expanded at Level 2 , Level 3.

#### Design

Now that we have a high level view on what the app should do, let us design the UI for the apps.

App Structure :As noted in Dashboard Design document, we will go with the following structure for the app

-   Menus :

    -   Introduction

    -   Injuries Dashboard (for daily/weekly users)

    <!-- -->

        -   Basic Stats

        -   Predictions

    -   Research

    -   Data Exploration

    -   Model Monitor

    -   Credits

#### Base Artifacts

Most shiny apps will get developed after some initial analysis (typically in RMD files) is done and you are now in the mode of exposing this analysis to wide user base. So , now that we have some initial idea of the user base let us take stock of what data and analysis artifacts we have created in-so-far

1.  RMD Files :
2.  Datasets :
3.  Models :

#### Skeleton App

Lets start with the Skeleton App.
